<?php

/**
 * PluginDmPollTemplateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmPollTemplateTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmPollTemplateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmPollTemplate');
    }
}