DmPollTemplate:
  actAs:
    Timestampable:
    I18n:
      fields: [title,question,answers]
      actAs:
        Timestampable:
        DmVersionable:
  columns:
    title: {type: string(100), notnull: true}
    question: {type: string(100),notnull: true}
    answers: {type: clob, notnull: true}
 
DmPollResults:
  actAs:
    Timestampable:
  columns:
    culture: {type: string(2), notnull: true}
    question: {type: integer,notnull: true}
    answer: {type: string(50)}
  relations:
    Question:
      class: DmPollTemplate
      local: question
      foreignAlias: Questions
 